api:
  dashboard: true
  debug: true
entryPoints:
  http:
    address: ":80"
    http:
      middlewares:
        - domain-redirect@file
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
    http:
      tls:
        domains:
          - main: docker.quantumlyconfused.com
      middlewares:
        - domain-redirect@file
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true
    allowEmptyServices: true
    defaultRule:  "Host(`{{ index .Labels \"com.docker.compose.service\" }}`) || Host(`{{ index .Labels \"com.docker.compose.service\" }}.docker.quantumlyconfused.com`)"
  file:
    filename: /traefik/config/config.yml
certificatesResolvers:
  cf:
    acme:
      email: padraignix@gmail.com
      storage: /traefik/data/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 10
        disablePropagationCheck: true
