version: "3.3"
services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=America/Toronto
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
      - LEGO_EXPERIMENTAL_CNAME_SUPPORT=true
    networks:
      - full_network
    ports:
      - "80:80"
      - "443:443"
      - "8888:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/padraignix/traefik/traefik.yml:/traefik.yml:ro
      - /home/padraignix/traefik/config.yml:/config.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.docker.quantumlyconfused.com`)"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.docker.quantumlyconfused.com`)"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cf"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=docker.quantumlyconfused.com"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.docker.quantumlyconfused.com"
      - "traefik.http.routers.traefik-secure.service=api@internal"

    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    restart: unless-stopped

networks:
  full_network:
    external: true